name: PR/CI Check

on:
  pull_request:
  push:
    branches-ignore:
      - main
      - release*

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
          - os: windows-latest
            target: aarch64-pc-windows-msvc
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
          #   - os: ubuntu-latest
          #     target: aarch64-unknown-linux-gnu
          #   - os: ubuntu-latest
          #     target: arm-unknown-linux-gnueabihf
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: macos-14
            target: aarch64-apple-darwin
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            vsix-target: alpine-x64
          #   - os: ubuntu-latest
          #     target: aarch64-unknown-linux-musl
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Rust Tool Chain setup
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: ${{ matrix.target }}

      - name: Cargo Fetch
        run: cargo fetch --frozen --all-features

      - name: Run Tests
        run: cargo test --all-features


  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Rust Tool Chain setup
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Install clippy
        run: rustup component add clippy

      - name: Cargo Fetch
        run: cargo fetch --frozen --all-features

      - name: Run Clippy
        run: cargo clippy --all-features -- -D warnings

  
  format-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Rust Tool Chain setup
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      
      - name: Check
        run: cargo fmt --all -- --check
